import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/analytics_models.dart';
import '../models/measurement_record_model.dart';
import '../models/measurement_session_model.dart';
import '../models/template_model.dart';
import '../utils/analytics/duration_format.dart';

class PdfReportService {
  static final RegExp _illegalFileChars = RegExp(r'[\\/:*?"<>|]');

  static String _safeFilePart(String raw) {
    final replaced = raw.trim().replaceAll(_illegalFileChars, '_');
    final compact = replaced.replaceAll(RegExp(r'\s+'), '_');
    return compact.isEmpty ? 'template' : compact;
  }

  static String _secondsText(int ms) => (ms / 1000.0).toStringAsFixed(2);

  static Future<File> exportSessionReportPdf({
    required MeasurementSessionModel session,
    required TemplateModel template,
    required List<MeasurementRecordModel> records,
    required SessionAnalytics analytics,
  }) async {
    final doc = pw.Document();
    final regularFont = pw.Font.ttf(await rootBundle.load('assets/fonts/arial.ttf'));
    final boldFont = pw.Font.ttf(await rootBundle.load('assets/fonts/arialbd.ttf'));
    final baseTheme = pw.ThemeData.withFont(
      base: regularFont,
      bold: boldFont,
    );
    final df = DateFormat('yyyy-MM-dd HH:mm:ss');
    final now = DateTime.now();
    final limitedRecords = records.take(300).toList();

    final cycleTotals = <int, int>{};
    for (final r in records) {
      cycleTotals.update(r.cycleNumber, (v) => v + r.durationMs, ifAbsent: () => r.durationMs);
    }
    final cycleValues = cycleTotals.values.toList()..sort();
    final minCycle = cycleValues.isEmpty ? 0 : cycleValues.first;
    final maxCycle = cycleValues.isEmpty ? 0 : cycleValues.last;
    final bottleneck = analytics.operations.isEmpty ? null : analytics.operations.first;
    final bottleneckPercent = bottleneck?.percentOfCycle.toStringAsFixed(0) ?? '0';

    final accent = PdfColor.fromInt(0xFFFFC107);

    final opOrder = <String>[];
    final values = <String, Map<int, MeasurementRecordModel>>{};
    final cyclesSet = <int>{};
    for (final r in limitedRecords) {
      cyclesSet.add(r.cycleNumber);
      values.putIfAbsent(r.operationName, () {
        opOrder.add(r.operationName);
        return <int, MeasurementRecordModel>{};
      });
      values[r.operationName]![r.cycleNumber] = r;
    }
    final cycles = cyclesSet.toList()..sort();

    pw.Widget labeled(String k, String v) {
      return pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.SizedBox(
              width: 130,
              child: pw.Text(
                k,
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.Expanded(child: pw.Text(v)),
          ],
        ),
      );
    }

    doc.addPage(
      pw.MultiPage(
        theme: baseTheme,
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Generated by TaktFlow',
            style: const pw.TextStyle(fontSize: 9),
          ),
        ),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.only(bottom: 8),
            decoration: const pw.BoxDecoration(
              border: pw.Border(bottom: pw.BorderSide(width: 1)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'TaktFlow Report',
                style: pw.TextStyle(
                    fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                    color: accent,
                  ),
                ),
                pw.Text(df.format(now)),
              ],
            ),
          ),
          pw.SizedBox(height: 12),
          labeled('Шаблон', template.name),
          labeled('Дата замера', DateFormat('yyyy-MM-dd').format(session.startedAt.toLocal())),
          labeled('Время начала', DateFormat('HH:mm:ss').format(session.startedAt.toLocal())),
          labeled('Количество циклов', '${analytics.completedCyclesCount}'),
          labeled('Количество операций', '${analytics.operations.length}'),
          labeled('Количество записей', '${records.length}'),
          pw.SizedBox(height: 12),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey700),
              color: PdfColors.grey100,
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Средний цикл: ${formatDurationMs(analytics.averageCycleMs)}'),
                pw.Text('Минимальный цикл: ${formatDurationMs(minCycle)}'),
                pw.Text('Максимальный цикл: ${formatDurationMs(maxCycle)}'),
                pw.Text(
                  'Узкое место: ${analytics.bottleneckOperationName} — '
                  '${formatDurationMs(analytics.bottleneckAverageMs)} ($bottleneckPercent%)',
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 14),
          pw.Text(
            'Аналитика операций',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 6),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headerDecoration: pw.BoxDecoration(color: PdfColors.grey300),
            cellPadding: const pw.EdgeInsets.all(4),
            headers: ['Операция', 'Среднее', 'Мин', 'Макс', 'Разброс', '% цикла', 'n'],
            data: analytics.operations
                .map(
                  (o) => [
                    o.operationName,
                    formatDurationMs(o.averageMs),
                    formatDurationMs(o.minMs),
                    formatDurationMs(o.maxMs),
                    formatDurationMs(o.spreadMs),
                    '${o.percentOfCycle.toStringAsFixed(0)}%',
                    '${o.count}',
                  ],
                )
                .toList(),
          ),
          pw.SizedBox(height: 12),
          pw.Text('Raw Data (циклы вбок)', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 6),
          if (records.length > 300)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 6),
              child: pw.Text('Показаны первые 300 записей из ${records.length}'),
            ),
          ..._buildCycleMatrixTables(
            operationOrder: opOrder,
            cycles: cycles,
            values: values,
          ),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final stamp = DateFormat('yyyyMMdd_HHmm').format(session.startedAt.toLocal());
    final safeTemplate = _safeFilePart(template.name);
    final file = File('${dir.path}/taktflow_report_${safeTemplate}_$stamp.pdf');
    await file.writeAsBytes(await doc.save(), flush: true);
    return file;
  }

  static List<pw.Widget> _buildCycleMatrixTables({
    required List<String> operationOrder,
    required List<int> cycles,
    required Map<String, Map<int, MeasurementRecordModel>> values,
  }) {
    if (operationOrder.isEmpty || cycles.isEmpty) {
      return [pw.Text('Нет строк для таблицы.')];
    }

    const chunkSize = 8;
    final widgets = <pw.Widget>[];
    for (var start = 0; start < cycles.length; start += chunkSize) {
      final end = (start + chunkSize > cycles.length) ? cycles.length : start + chunkSize;
      final chunk = cycles.sublist(start, end);

      widgets.add(
        pw.Text(
          'Циклы ${chunk.first}–${chunk.last}',
          style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
        ),
      );
      widgets.add(pw.SizedBox(height: 4));
      widgets.add(
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          headerDecoration: pw.BoxDecoration(color: PdfColors.grey300),
          cellPadding: const pw.EdgeInsets.all(4),
          headers: ['Операция', ...chunk.map((c) => 'Ц$c')],
          data: operationOrder.map((opName) {
            return [
              opName,
              ...chunk.map((c) {
                final rec = values[opName]?[c];
                return rec == null ? '' : _secondsText(rec.durationMs);
              }),
            ];
          }).toList(),
        ),
      );
      widgets.add(pw.SizedBox(height: 10));
    }
    return widgets;
  }
}
